### ISSUE TITLE
Display winner after game end

### ISSUE THREAD

**Issue by matthewjwolff** [DRMold/HungryHungryTetris#10]
@DRMold Tagging to participate in issue

**Comment by mhfirdausi** [comment]
[032ec18](https://github.com/DRMold/HungryHungryTetris/commit/032ec18064eca56878add41d742bc09cd3eb52f3): 2016-04-04
Added initial game over panel, restart and main menu buttons functional.
- Currently overlays over entire scene. Need to implement transition.
- Does not show scores or victor yet.

**Comment by mhfirdausi** [comment]
[0418f6d](https://github.com/DRMold/HungryHungryTetris/commit/0418f6d23610fd0ff1437ef4f4b7b996fb709870) 2016 - 04 - 04

Game over panel is now not shown and not interactable on game start. When GameOver event is triggered, the panel fades in, shows a dummy score, and allows users to interact.
- Does not show actual scores or victor yet.
- Can be triggered by keypress, future iteration should be triggered in game.

**Comment by mhfirdausi** [comment]
[899f53d](https://github.com/DRMold/HungryHungryTetris/commit/899f53ddaff333b959451a1c9622263ffbdf4bb6) 2016 - 04 - 22

Updated the game over panel. 
- On game over the game over panel attempts to retrieve the scores from the in game score panels. NOT TESTED WITH MASTER YET
- If the timer runs out, scores are compared and panels will change states to reflect the winner of the game. NOT TESTED WITH MASTER YET
- Right now there is no way to determine who wins when a player's blocks hit the top of their arena

**Comment by mhfirdausi** [comment]
Can't close this yet - right now there is still no way to trigger game over/winner conditions when P1/P2 hit the top of their arenas. Also, the scene in the latest commit is missing some references and doesn't trigger game over correctly.

**Comment by mhfirdausi** [comment]
[1c7a624](https://github.com/DRMold/HungryHungryTetris/commit/1c7a624466dca5d4d0abe258fb5dbe1331fd5406) 2016 - 04 - 27

Merge in everything! Have a (mostly) functional game over panel!
