### ISSUE TITLE
Penalization for Empty Queue

### ISSUE THREAD

**Issue by matthewjwolff** [DRMold/HungryHungryTetris#13]
Possibilities include raising the floor / creating a row of indestructable blocks at the bottom.

Importance should be given to the player's ability to determine why the negative action was applied to them. It would be bad if the player couldn't determine why a row of blocks "randomly" spawned.

**Comment by matthewjwolff** [comment]
@DRMold for participation

**Comment by ThomasCulotta** [comment]
extra check to catch blocks raised above gameoverheight on genbottomandraiseblocks
