### ISSUE TITLE
Return to Main Menu after game end

### ISSUE THREAD

**Issue by matthewjwolff** [DRMold/HungryHungryTetris#7]

**Comment by mhfirdausi** [comment]
[032ec18](https://github.com/DRMold/HungryHungryTetris/commit/032ec18064eca56878add41d742bc09cd3eb52f3) 2016 - 04 - 04

Game over screen in UI branch allows either restarting or going back to main menu. See issue 10 [here](https://github.com/DRMold/HungryHungryTetris/issues/10) for further development process on game over screen.
