### ISSUE TITLE
Timer / Score Display

### ISSUE THREAD

**Issue by matthewjwolff** [DRMold/HungryHungryTetris#9]
Includes toggleable settings in options menu

**Comment by matthewjwolff** [comment]
Commenting to participate in this issue

**Comment by mhfirdausi** [comment]
[b63ca1f](https://github.com/DRMold/HungryHungryTetris/commit/b63ca1f78428bcf45d4d24dd3f67dfd4d0804745) 2016 - 04 - 13
- Initial time and score panels are in a separate scene. Do we went a separate timer sprite element? Do we want to show the time in seconds or split into minute:second format?
- Timer integration does not currently work with the "updated time" of the GameMaster.

**Comment by mhfirdausi** [comment]
[899f53d](https://github.com/DRMold/HungryHungryTetris/commit/899f53ddaff333b959451a1c9622263ffbdf4bb6) 2016 - 04 - 22
- Timer panels can be set in the menu and count down on the scene start. On the end of the countdown, the game over panel is triggered and attempts to get the score from the score panels.
